### ISSUE TITLE
Linking against libstdc++fs is not always required

### ISSUE THREAD

**Issue by tristan0x** [1uc/ZisaSFC#9]
The line below introduces a compilation issue on MacOS arm64 with AppleClang 15.0.0. The linker cannot find the `libstd++fs` library.

https://github.com/1uc/ZisaSFC/blob/9ad1d659a2c9dc879348d388c509b3f26ce7388d/CMakeLists.txt#L17

---
You can get inspiration from pybind11 heuristic to determine whether the linking is required:
https://github.com/pybind/pybind11/blob/f29def9ea467c7fde754440733047953fa4b990c/tests/CMakeLists.txt#L342-L366

**Comment by 1uc** [comment]
I don't think it's needed at all, see #10. Likely it's a hold over from splitting Zisa into "reusable" parts.
